<head>
    <title><?php if (isset ($this->metaTitle)) echo $this->escape ($this->metaTitle);?></title>
    <meta name="description" content="<?php if (isset ($this->metaDescription)) echo $this->escape ($this->metaDescription);?>" />

    <meta charset="UTF-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

    <?php foreach ($this->design ()->getCss ('head') as $entry):?>
        <link type="text/css" rel="stylesheet"<?php echo $this->renderAttr ($entry);?> />
    <?php endforeach;?>

    <?php foreach ($this->design ()->getJs ('head') as $entry):?>
        <script type="text/javascript"<?php echo $this->renderAttr ($entry);?>></script>
    <?php endforeach;?>
</head>