<!DOCTYPE HTML>
<html lang="fr">
    <?php echo $this->renderTemplate ('html/head');?>
    <body>
        <?php echo $this->renderTemplate ('html/navbar');?>
        <div class="container">
            <?php echo $this->getContent ();?>
        </div>
        <?php echo $this->renderTemplate ('html/footer');?>
        <?php echo $this->renderTemplate ('html/javascript');?>
    </body>
</html>